name: Update Blocklist

on:
  schedule:
    - cron: '0 6 * * 0'  # Weekly on Sunday at 6am UTC
  workflow_dispatch:      # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lists/
          git diff --staged --quiet || git commit -m "Update blocklist - $(date -u '+%Y-%m-%d')"
          git push
